services:
  supabase-grafana:
    image: grafana/grafana:latest
    environment:
      SUPABASE_ACCESS_TOKEN: ${SUPABASE_ACCESS_TOKEN}
      SUPABASE_ORGANIZATION_ID: ${SUPABASE_ORGANIZATION_ID}
      SUPABASE_PROJECT_REF: ${SUPABASE_PROJECT_REF}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      PASSWORD_PROTECTED: ${PASSWORD_PROTECTED}
      GRAFANA_PASSWORD: ${GRAFANA_PASSWORD}
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
